### ISSUE TITLE
Unexpected behaviour: AutoGame triggers with both inbound and outbound connections.

### ISSUE THREAD

**Issue by jordantgh** [jarrettgilliam/AutoGame#12]
I have a PC (PC1) that I use as both a client and as a host. I was expecting AutoGame to trigger on PC1 only when I use another PC (e.g., PC2) as a client to connect to PC1. However, I observed that AutoGame also triggers when I use PC1 as a client to connect to PC2. Is there a way to configure AutoGame such that it reacts to only inbound Parsec connections?

**Comment by jarrettgilliam** [comment]
Unfortunately no. Not as it is now. This is an issue I've known about for awhile but haven't gotten around to solving. Mostly because it's kind of a tricky problem. Both hosts and clients have active UDP ports and audio sessions, the two things it's looking for to determine if Parsec is connected. It's kind of left me scratching my head wondering what else I could have it check for. I'll give this issue another shot and see if I can come up with a reliable way to differentiate the two.

**Comment by jarrettgilliam** [comment]
OK, this should be fixed in release v2.0.1. When you get a minute, let me know if it works for you too.

**Comment by jordantgh** [comment]
Hey, that was fast. Did you push it as an autoupdate? Because it does now seem to be exhibiting the expected behaviour, although I didn't (manually) download the latest release. 

EDIT: Nevermind, I can see from my local files that it hasn't been updated since 24/06/22 on my system. It's funny, I have no idea why I'm not reproducing the original bug. I'll take a closer look tomorrow. Well done anyway on getting on it so fast.
