### ISSUE TITLE
Parsec config can prevent ParsecConnectedCondition.cs's event listeners from triggering

### ISSUE THREAD

**Issue by Wynadorn** [jarrettgilliam/AutoGame#3]
Great application, exactly what I was looking for although initially it wouldn't work for me. Quickly found out it was due to my Parsec config.txt, which contains:

```
server_resolution_x=-1
server_resolution_y=-1
server_admin_mute=0
```
These settings prevent your **speakers from being muted** and **preserve the host's resolution**.
Which, of course, prevents both event listeners that point to `this.CheckConditionMet();` from being triggered.

Was wondering if you have thought any extra events that the application could possibly be listening for. Maybe it'd be possible to listen for a new UDP connection directly.

For now I've just set `server_admin_mute=1` as a workaround.

**Comment by jarrettgilliam** [comment]
Thanks for submitting an issue! I could definitely add more event listeners. I figured those two would cover most people. Evidently I was wrong. 🙂

Here's what I'm thinking:

1. Listen for new UDP connections like you suggested. If there is some system event for this, that would be ideal. I'd like to avoid polling if possible.
2. Listen for the Parsec connected notification in windows. UWP has an [API](https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/notification-listener) for this, but I think it requires admin rights. I'd like to avoid that as well. I've also turned those notification off on my system.
3. Listen for new active audio sessions. I'm doing something similar in `ParsecConnectedCondition.HasAnyActiveAudioSessions`. Maybe the `NAudio.CoreAudioApi.AudioSessionManager.OnSessionCreated` event could be useful. This is probably what I would try first.
4. Listen for new virtual input devices created by Parsec. Gamepads, mouse, keyboard, etc. Not sure how this would be done.

Unfortunately I won't have time to work on this until next weekend. If you come up with a solution before then, send me a pull request and I'll take a look. Otherwise I'll work on this then.

Thanks again!

**Comment by Wynadorn** [comment]
I had a look this afternoon, NAudio.CoreAudioApi.AudioSessionManager.OnSessionCreated wasn't fired, at least not in the way I had implemented it. Next I had a look at the Parsec SDK: https://github.com/parsec-cloud/parsec-sdk

I was unable to add the Windows libraries, possibly because they're not compatible with .NET core.
![image](https://user-images.githubusercontent.com/4095127/134340581-c60d27af-0a54-44f2-b84a-53d5a1528ea9.png)

I was however able to add the ParsecUnity46.dll, there's some interesting events:
![image](https://user-images.githubusercontent.com/4095127/134340939-f125f2f4-738e-4b05-bca3-7a62ad429025.png)

However I believe it has a dependency to the UnityEngine, so sadly wasn't able to use it.
![image](https://user-images.githubusercontent.com/4095127/134341157-f4aed6a2-b6ab-473c-b999-1afcf4ba4ddc.png)
`CS0012	The type 'MonoBehaviour' is defined in an assembly that is not referenced. You must add a reference to assembly 'UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.`

You'd think there'd be a solution to this use case somewhere in Parsec already. All we'd really need is the ability to have the host run a application / script when a remote connection gets established. Could be one line in the config file.

I was also thinking about how other gaming systems' UIs have been implemented. Usually you'd have a home button, to go back to a menu where you can quit your current game and go back to the main menu. Maybe this could be a solution, because then you'd have a way to regain control no matter what state the host system is in. I haven't tested it yet, but for an Xbox one controller it'd be the guide / xbox button at the top.

**Comment by jarrettgilliam** [comment]
The Parsec SDK was one of the first things I looked into. I was never able to get it to work. I think it's meant for creating parsec connections outside of the official client. Pretty cool in general but not very helpful for me. I assume the Unity version does something similar.

Anyway, I spend some time this morning and I think I have a fix for this. I was able to use the `OnSessionCreated` event in tandem with the `AudioSessionControl.RegisterEventClient()` method to listen for state changes on the Parsec audio session. After debugging this, it looks like Parsec creates the audio session when it starts up, but leaves it in an inactive state. When a client connects, that session goes to active. Using both events together seems to pretty reliably detect connections even when the original display and mute events don't fire.

I went ahead and created a new release. Let me know if it works for you and I'll close this issue. 🙂

**Comment by Wynadorn** [comment]
Just tested it, works well, thanks!
